spring:
 mvc:
  throw-exception-if-no-handler-found: true

graphql:
 servlet:
   mapping: /api/graphql
   enabled: true

graphiql:
 mapping: /graphiql
 endpoint: /api/graphql
 enabled: true

voyager:
 mapping: /voyager
 endpoint: /api/graphql
 enabled: true